### ISSUE TITLE
Uncaught TypeError: can't access property "prototype", a is undefined

### ISSUE THREAD

**Issue by jurkotroll** [bearz/slate-cljs-minimal-example#2]
Hi,
is this work? I get error **`Uncaught TypeError: can't access property "prototype", a is undefined`**.
I've tried other ways to adopt this lib for CLJS, but no success either.
Just curies am I doing something wrong or it some bugs in `Slate`?

**Comment by shvets-sergey** [comment]
I had the same issue and actually created this repo so Thomas Heller can take a look (he is amazing). The fix is to have `{:compiler-options {:output-feature-set :es6}}` in your `shadow-cljs.edn` config. It seems that slate with migration to TypeScript now requires the es6 syntax. I updated the repo to have this option and you should be able to pull it and play with it now. 

Hope this helps!

**Comment by jurkotroll** [comment]
Thanks! This works. I'll try fix in my project, but guest this is it. Would you merge fixed version or should I just fork this?

**Comment by shvets-sergey** [comment]
I already updated it. See the latest commit.
